### PR TITLE
fix(fgw): include `l1_to_l2_consumed_message` in L1 handler receipt

### LINKED ISSUE #375: bug(fgw): inconsistent L1Handler tx receipt
### Is there an existing issue?

- [X] I have searched the existing issues

### Description of bug

`l1_to_l2_consumed_message` is not stored in the database for receipts related to L1_handler_tx. The FGW does not return l1_to_l2_consumed_message.
the consumed message can be derived from the L1 handler transaction data.

### Steps to reproduce

_No response_

### PR DESCRIPTION
**Pull request by jbcaron**
## Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Bugfix

## What is the current behavior?

the `l1_to_l2_consumed_message` field is missing in the FGW receipt

Resolves: #375 

## What is the new behavior?

retrieve the `l1_to_l2_consumed_message` directly from the L1 handler transaction

## Does this introduce a breaking change?

No

## Other information

**⚠️ merge #380 before**

### CODE REVIEW

File: crates/primitives/convert/src/felt.rs [hunk 1]
```diff
@@ -24,6 +25,23 @@ pub fn felt_to_u128(felt: &Felt) -> Result<u128, FeltToU128Error> {
...
 
+#[derive(Debug, thiserror::Error)]
+#[error("Felt is too big to convert to H160.")]
+pub struct FeltToH160Error;
+
+pub fn felt_to_h160(felt: &Felt) -> Result<H160, FeltToH160Error> {
+    let bytes = felt.to_bytes_be();
+
+    // check if the 12 first bytes are null
+    if !bytes.iter().take(12).all(|&b| b == 0) {
```
Comment (Trantorian1) [inline crates/primitives/convert/src/felt.rs]: Why not a simple comparison of the type `felt > 2^160 - 1` (pseudocode) with a static `from_hex_unchecked` ?

File: crates/primitives/convert/src/lib.rs [hunk 2]
```diff
@@ -2,7 +2,7 @@ mod felt;
 pub mod hex_serde;
 mod to_felt;
 
-pub use felt::{felt_to_u128, felt_to_u64};
+pub use felt::{felt_to_h160, felt_to_u128, felt_to_u64};
```
Comment (Trantorian1) [inline crates/primitives/convert/src/lib.rs]: This should be merged after #380

**Review by Trantorian1 — CHANGES_REQUESTED** [review]
Seems good, small fix for `felt_to_h160`.

**Review by cchudant — APPROVED** [review]
how did we miss that when comparing what the starkware fgw and ours returns?

File: crates/primitives/convert/src/felt.rs (hunk 1 above)
Comment (jbcaron) [reply crates/primitives/convert/src/felt.rs]: checking the first 12 bytes for nulls directly aligns with the H160 conversion logic, ensuring clarity and structural validation, whereas a numeric comparison obscures this intent

Comment (jbcaron) [reply crates/primitives/convert/src/felt.rs]: You’re right

**Comment by Trantorian1** [comment]
> how did we miss that when comparing what the starkware fgw and ours returns?

No specs :D

**Review by Trantorian1 — APPROVED** [review]
All good :+1:
