### PR TITLE
Fix batched reqs

### LINKED ISSUE #313: feat: support batched requests (needed for voyager)
### Is there an existing issue?

- [X] I have searched the existing issues

### Motivation

Voyager uses batched requests currently to sync with the chain. Not having it makes us incompatible with it.

### Request

We need to add support in Voyager to allow batched JSON RPC requests. This means you can send requests in the format

EDIT: I noticed we already have batch request support [here](https://github.com/madara-alliance/madara/blob/567e472ee5c7e356ebbf24d6a3b7e293a80e8ed6/crates/node/src/cli/rpc.rs#L147). But it doesn't seem to work as expected based on the request format below.

```curl
curl --location 'http://localhost:6060' \
--header 'Content-Type: application/json' \
--data '[
    {
        "jsonrpc": "2.0",
        "method": "starknet_getBlockWithTxs",
        "params": [
            {
                "block_number": 0
            }
        ],
        "id": 0
    },
    {
        "jsonrpc": "2.0",
        "method": "starknet_getBlockWithTxHashes",
        "params": [
            "latest"
        ],
        "id": 1
    }
]'
```

and get a response like

```
[
    {
        "jsonrpc": "2.0",
        "result": {
            "status": "ACCEPTED_ON_L2",
            "block_hash": "0x47c3637b57c2b079b93c61539950c17e868a28f46cdef28f88521067f21e943",
            "parent_hash": "0x0",
            "block_number": 0,
            "new_root": "0x21870ba80540e7831fb21c591ee93481f5ae1bb71ff85a86ddd465be4eddee6",
            "timestamp": 1637069048,
            "sequencer_address": "0x0",
            "l1_gas_price": {
                "price_in_fri": "0x0",
                "price_in_wei": "0x0"
            },
            "l1_data_gas_price": {
                "price_in_fri": "0x1",
                "price_in_wei": "0x1"
            },
            "l1_da_mode": "CALLDATA",
            "starknet_version": "",
            "transactions": [
                {
                    "transaction_hash": "0xe0a2e45a80bb827967e096bcf58874f6c01c191e0a0530624cba66a508ae75",
                    "type": "DEPLOY",
                    "version": "0x0",
                    "contract_address_salt": "0x546c86dc6e40a5e5492b782d8964e9a4274ff6ecb16d31eb09cee45a3564015",
                    "class_hash": "0x10455c752b86932ce552f2b0fe81a880746649b9aee7e0d842bf3f52378f9f8",
                    "constructor_calldata": [
                        "0x6cf6c2f36d36b08e591e4489e92ca882bb67b9c39a3afccf011972a8de467f0",
                        "0x7ab344d88124307c07b56f6c59c12f4543e9c96398727854a322dea82c73240"
                    ]
                },
                {
                    "transaction_hash": "0x12c96ae3c050771689eb261c9bf78fac2580708c7f1f3d69a9647d8be59f1e1",
                    "type": "DEPLOY",
                    "version": "0x0",
                    "contract_address_salt": "0x12afa0f342ece0468ca9810f0ea59f9c7204af32d1b8b0d318c4f2fe1f384e",
                    "class_hash": "0x10455c752b86932ce552f2b0fe81a880746649b9aee7e0d842bf3f52378f9f8",
                    "constructor_calldata": [
                        "0xcfc2e2866fd08bfb4ac73b70e0c136e326ae18fc797a2c090c8811c695577e",
                        "0x5f1dd5a5aef88e0498eeca4e7b2ea0fa7110608c11531278742f0b5499af4b3"
                    ]
                },
                {
                    "transaction_hash": "0xce54bbc5647e1c1ea4276c01a708523f740db0ff5474c77734f73beec2624",
                    "type": "INVOKE",
                    "version": "0x0",
                    "max_fee": "0x0",
                    "contract_address": "0x20cfa74ee3564b4cd5435cdace0f9c4d43b939620e4a0bb5076105df0a626c6",
                    "signature": [],
                    "calldata": [
                        "0xc84dd7fd43a7defb5b7a15c4fbbe11cbba6db1ba"
                    ],
                    "entry_point_selector": "0x12ead94ae9d3f9d2bdb6b847cf255f1f398193a1f88884a0ae8e18f24a037b6"
                },
                {
                    "transaction_hash": "0x1c924916a84ef42a3d25d29c5d1085fe212de04feadc6e88d4c7a6e5b9039bf",
                    "type": "INVOKE",
                    "version": "0x0",
                    "max_fee": "0x0",
                    "contract_address": "0x31c9cdb9b00cb35cf31c05855c0ec3ecf6f7952a1ce6e3c53c3455fcd75a280",
                    "signature": [],
                    "calldata": [
                        "0x20cfa74ee3564b4cd5435cdace0f9c4d43b939620e4a0bb5076105df0a626c6",
                        "0x0"
                    ],
                    "entry_point_selector": "0x218f305395474a84a39307fa5297be118fe17bf65e27ac5e2de6617baa44c64"
                },
                {
                    "transaction_hash": "0xa66c346e273cc49510ef2e1620a1a7922135cb86ab227b86e0afd12243bd90",
                    "type": "INVOKE",
                    "version": "0x0",
                    "max_fee": "0x0",
                    "contract_address": "0x20cfa74ee3564b4cd5435cdace0f9c4d43b939620e4a0bb5076105df0a626c6",
                    "signature": [],
                    "calldata": [
                        "0x7dbfec95c10bbc2fd3f37a89ae6e027826134f955251d11c784a6b34fdf50",
                        "0x2",
                        "0x4e7e989d58a17cd279eca440c5eaa829efb6f9967aaad89022acbe644c39b36",
                        "0x453ae0c9610197b18b13645c44d3d0a407083d96562e8752aab3fab616cecb0"
                    ],
                    "entry_point_selector": "0x317eb442b72a9fae758d4fb26830ed0d9f31c8e7da4dbff4e8c59ea6a158e7f"
                },
                {
                    "transaction_hash": "0x5c71675616b49fb9d16cac8beaaa65f62dc5a532e92785055c15c825166dbbf",
                    "type": "INVOKE",
                    "version": "0x0",
                    "max_fee": "0x0",
                    "contract_address": "0x31c9cdb9b00cb35cf31c05855c0ec3ecf6f7952a1ce6e3c53c3455fcd75a280",
                    "signature": [],
                    "calldata": [
                        "0x31c9cdb9b00cb35cf31c05855c0ec3ecf6f7952a1ce6e3c53c3455fcd75a280",
                        "0x317eb442b72a9fae758d4fb26830ed0d9f31c8e7da4dbff4e8c59ea6a158e7f",
                        "0x4",
                        "0x4be52041fee36ab5199771acf4b5d260d223297e588654e5c9477df2efa542a",
                        "0x2",
                        "0x299e2f4b5a873e95e65eb03d31e532ea2cde43b498b50cd3161145db5542a5",
                        "0x3d6897cf23da3bf4fd35cc7a43ccaf7c5eaf8f7c5b9031ac9b09a929204175f"
                    ],
                    "entry_point_selector": "0x27c3334165536f239cfd400ed956eabff55fc60de4fb56728b6a4f6b87db01c"
                },
                {
                    "transaction_hash": "0x60e05c41a6622592a2e2eff90a9f2e495296a3be9596e7bc4dfbafce00d7a6a",
                    "type": "INVOKE",
                    "version": "0x0",
                    "max_fee": "0x0",
                    "contract_address": "0x31c9cdb9b00cb35cf31c05855c0ec3ecf6f7952a1ce6e3c53c3455fcd75a280",
                    "signature": [],
                    "calldata": [
                        "0x20cfa74ee3564b4cd5435cdace0f9c4d43b939620e4a0bb5076105df0a626c6",
                        "0x1"
                    ],
                    "entry_point_selector": "0x218f305395474a84a39307fa5297be118fe17bf65e27ac5e2de6617baa44c64"
                },
                {
                    "transaction_hash": "0x5634f2847140263ba59480ad4781dacc9991d0365145489b27a198ebed2f969",
                    "type": "INVOKE",
                    "version": "0x0",
                    "max_fee": "0x0",
                    "contract_address": "0x31c9cdb9b00cb35cf31c05855c0ec3ecf6f7952a1ce6e3c53c3455fcd75a280",
                    "signature": [],
                    "calldata": [
                        "0x20cfa74ee3564b4cd5435cdace0f9c4d43b939620e4a0bb5076105df0a626c6",
                        "0x5aee31408163292105d875070f98cb48275b8c87e80380b78d30647e05854d5"
                    ],
                    "entry_point_selector": "0x19a35a6e95cb7a3318dbb244f20975a1cd8587cc6b5259f15f61d7beb7ee43b"
                },
                {
                    "transaction_hash": "0xb049c384cf75174150a2540835cc2abdcca1d3a3750298a1741a621983e35a",
                    "type": "DEPLOY",
                    "version": "0x0",
                    "contract_address_salt": "0x5098705e4d57a8620e5b387855ef4dc82f0ccd84b7299dc1179b87517249127",
                    "class_hash": "0x10455c752b86932ce552f2b0fe81a880746649b9aee7e0d842bf3f52378f9f8",
                    "constructor_calldata": [
                        "0x48cba68d4e86764105adcdcf641ab67b581a55a4f367203647549c8bf1feea2",
                        "0x362d24a3b030998ac75e838955dfee19ec5b6eceb235b9bfbeccf51b6304d0b"
                    ]
                },
                {
                    "transaction_hash": "0x227f3d9d5ce6680bdf2991576c1a90aca8184ca26055bae92d16c58e3e13340",
                    "type": "DEPLOY",
                    "version": "0x0",
                    "contract_address_salt": "0x60bc7461113e4af46fd52e5ecbc5c3f4be92ed7f1329d53721f9bfbc0370cc",
                    "class_hash": "0x10455c752b86932ce552f2b0fe81a880746649b9aee7e0d842bf3f52378f9f8",
                    "constructor_calldata": [
                        "0x2f50710449a06a9fa789b3c029a63bd0b1f722f46505828a9f815cf91b31d8",
                        "0x2a222e62eabe91abdb6838fa8b267ffe81a6eb575f61e96ec9aa4460c0925a2"
                    ]
                },
                {
                    "transaction_hash": "0x376ff82431b52ca1fbc4942de80bc1b01d8e5cd1eeab5a277b601b510f2cab2",
                    "type": "INVOKE",
                    "version": "0x0",
                    "max_fee": "0x0",
                    "contract_address": "0x6ee3440b08a9c805305449ec7f7003f27e9f7e287b83610952ec36bdc5a6bae",
                    "signature": [],
                    "calldata": [
                        "0x1e2cd4b3588e8f6f9c4e89fb0e293bf92018c96d7a93ee367d29a284223b6ff",
                        "0x71d1e9d188c784a0bde95c1d508877a0d93e9102b37213d1e13f3ebc54a7751"
                    ],
                    "entry_point_selector": "0x3d7905601c217734671143d457f0db37f7f8883112abd34b92c4abfeafde0c3"
                },
                {
                    "transaction_hash": "0x25f20c74821d84f62989a71fceef08c967837b63bae31b279a11343f10d874a",
                    "type": "DEPLOY",
                    "version": "0x0",
                    "contract_address_salt": "0x63d1a6f8130958509e2e695c25b147f43f66f56bba49fddb7ee363d8f57a774",
                    "class_hash": "0x10455c752b86932ce552f2b0fe81a880746649b9aee7e0d842bf3f52378f9f8",
                    "constructor_calldata": [
                        "0xdf28e613c065616a2e79ca72f9c1908e17b8c913972a9993da77588dc9cae9",
                        "0x1432126ac23c7028200e443169c2286f99cdb5a7bf22e607bcd724efa059040"
                    ]
                },
                {
                    "transaction_hash": "0x2d10272a8ba726793fd15aa23a1e3c42447d7483ebb0b49df8b987590fe0055",
                    "type": "INVOKE",
                    "version": "0x0",
                    "max_fee": "0x0",
                    "contract_address": "0x31c887d82502ceb218c06ebb46198da3f7b92864a8223746bc836dda3e34b52",
                    "signature": [],
                    "calldata": [
                        "0x735596016a37ee972c42adef6a3cf628c19bb3794369c65d2c82ba034aecf2c",
                        "0x1"
                    ],
                    "entry_point_selector": "0x218f305395474a84a39307fa5297be118fe17bf65e27ac5e2de6617baa44c64"
                },
                {
                    "transaction_hash": "0xb05ba5cd0b9e0464d2c1790ad93a159c6ef0594513758bca9111e74e4099d4",
                    "type": "INVOKE",
                    "version": "0x0",
                    "max_fee": "0x0",
                    "contract_address": "0x735596016a37ee972c42adef6a3cf628c19bb3794369c65d2c82ba034aecf2c",
                    "signature": [],
                    "calldata": [
                        "0x31c887d82502ceb218c06ebb46198da3f7b92864a8223746bc836dda3e34b52",
                        "0x0"
                    ],
                    "entry_point_selector": "0x218f305395474a84a39307fa5297be118fe17bf65e27ac5e2de6617baa44c64"
                },
                {
                    "transaction_hash": "0x4d16393d940fb4a97f20b9034e2a5e954201fee827b2b5c6daa38ec272e7c9c",
                    "type": "INVOKE",
                    "version": "0x0",
                    "max_fee": "0x0",
                    "contract_address": "0x6ee3440b08a9c805305449ec7f7003f27e9f7e287b83610952ec36bdc5a6bae",
                    "signature": [],
                    "calldata": [
                        "0x1a7cf8b8027ec2d8fd04f1277f3f8ae6379ca957c5fec9ee7f59d56d86a26e4",
                        "0x2",
                        "0x28dff6722aa73281b2cf84cac09950b71fa90512db294d2042119abdd9f4b87",
                        "0x57a8f8a019ccab5bfc6ff86c96b1392257abb8d5d110c01d326b94247af161c"
                    ],
                    "entry_point_selector": "0x317eb442b72a9fae758d4fb26830ed0d9f31c8e7da4dbff4e8c59ea6a158e7f"
                },
                {
                    "transaction_hash": "0x9e80672edd4927a79f5384e656416b066f8ef58238227ac0fcea01952b70b5",
                    "type": "INVOKE",
                    "version": "0x0",
                    "max_fee": "0x0",
                    "contract_address": "0x31c887d82502ceb218c06ebb46198da3f7b92864a8223746bc836dda3e34b52",
                    "signature": [],
                    "calldata": [
                        "0x6ee3440b08a9c805305449ec7f7003f27e9f7e287b83610952ec36bdc5a6bae",
                        "0x5f750dc13ed239fa6fc43ff6e10ae9125a33bd05ec034fc3bb4dd168df3505f"
                    ],
                    "entry_point_selector": "0x19a35a6e95cb7a3318dbb244f20975a1cd8587cc6b5259f15f61d7beb7ee43b"
                },
                {
                    "transaction_hash": "0x387b5b63e40d4426754895fe52adf668cf8fde2a02aa9b6d761873f31af3462",
                    "type": "INVOKE",
                    "version": "0x0",
                    "max_fee": "0x0",
                    "contract_address": "0x6ee3440b08a9c805305449ec7f7003f27e9f7e287b83610952ec36bdc5a6bae",
                    "signature": [],
                    "calldata": [
                        "0x449908c349e90f81ab13042b1e49dc251eb6e3e51092d9a40f86859f7f415b0",
                        "0x2670b3a8266d5046696a4b79f7433d117d3a19166f15bbd8585822c4e9b7491"
                    ],
                    "entry_point_selector": "0x3d7905601c217734671143d457f0db37f7f8883112abd34b92c4abfeafde0c3"
                },
                {
                    "transaction_hash": "0x4f0cdff0d72fc758413a16db2bc7580dfec7889a8b921f0fe08641fa265e997",
                    "type": "INVOKE",
                    "version": "0x0",
                    "max_fee": "0x0",
                    "contract_address": "0x6ee3440b08a9c805305449ec7f7003f27e9f7e287b83610952ec36bdc5a6bae",
                    "signature": [],
                    "calldata": [
                        "0x449908c349e90f81ab13042b1e49dc251eb6e3e51092d9a40f86859f7f415b0",
                        "0x6cb6104279e754967a721b52bcf5be525fdc11fa6db6ef5c3a4db832acf7804"
                    ],
                    "entry_point_selector": "0x3d7905601c217734671143d457f0db37f7f8883112abd34b92c4abfeafde0c3"
                }
            ]
        },
        "id": 0
    },
    {
        "jsonrpc": "2.0",
        "result": {
            "status": "ACCEPTED_ON_L2",
            "block_hash": "0x2a30e74c61c2babead8ff200a12ed681b5b0641056348a569dc942c4280bc90",
            "parent_hash": "0x6e30f85eb5fbaad16ec41c94224becd8cc11381fc64344fa5647a7215264ceb",
            "block_number": 5382,
            "new_root": "0x75185e365be2a25bb0f310674952772d5e5906147f5d319d7e5d52151664470",
            "timestamp": 1664486306,
            "sequencer_address": "0x5dcd266a80b8a5f29f04d779c6b166b80150c24f2180a75e82427242dab20a9",
            "l1_gas_price": {
                "price_in_fri": "0x0",
                "price_in_wei": "0xb55840861"
            },
            "l1_data_gas_price": {
                "price_in_fri": "0x1",
                "price_in_wei": "0x1"
            },
            "l1_da_mode": "CALLDATA",
            "starknet_version": "0.10.0",
            "transactions": [
                "0x641df6ede2f1e439ab3b24e96dcc8537edccd0f8955caeb090395ba920876ff",
                "0x5655c88f8fbb8f22dea25c52bc6a150b4965c7b6174137f309982d03e958315",
                "0x4c9016d43b3e98a4947cfc3eab516202de64db14098e04e1b25431ccc10e9cf",
                "0xce693b18999832d3cc0a3e40bc76a7ac063bb0157575c73f8ce05ec969c778",
                "0x4368a8aeb4f0c027600d2a047c373c48d9f983d1eba75f83a94d484b5d06f23",
                "0x5cf0a4096c34ad719a1bebc4c03541db27bd8022faf9599538bab3e9dad38d8",
                "0x4f7d071fede2d2b007343ebc7db7b0c03e6e4a30765a63c5501c2466d7a84e6",
                "0x53a49eb49cad408dfff230212416296ad4510694b0b69648e9a549cc03857d8",
                "0x5e5a1cd9ff4aad6842864e777a2c388d81774cb2b99662278dc253bb601b2af",
                "0x798b9f9b349176df4896f7f58d33057c2caf020440f9af71177e0b8e04ef14",
                "0x3831493c58abf7471cf67baf895bfb748a53e2377a651634a1b0a31294e3752",
                "0x30dc7379823dbeb676b3bfbb1ecd69e98932816df66120e966375e1f4c2d048",
                "0x7f65f0b892001ca238e9c0a8dc9afe76e618ced48be92fe908e9642e63382b1",
                "0x23d3f1435dfdb74650b828d1b4f7ffa99c5626abcf89a0bd0d85ae8a15699fb",
                "0x6272523206b5030cd0c1b4a3742d65804343895bcd0ef42f0f9f99ba4b28743",
                "0x105d274700f300d89f49855a64a54cce514b594b5d2343ef302deecf8e70149",
                "0x5f7cfd6cba84b99389a4c95ba64f16cb93b649bc9a45dcaea7927c362153102",
                "0x5d04e9d2094d3d8e9404f160d9fe4aea77ea3517b5ebf68790c64de01fc2a42",
                "0x63705c5039e3689786e9f2fa7d826644bfa59eba615bf2e2c9c4ac10c714b6d",
                "0x4f51ba8c628664be124bb009044dce7c7e81b7d62283349a17d198e0cf3d38d",
                "0x6258e07f87d642ffc36c83c50dc465191003469dd1c288744d1e740235b4186",
                "0x4f6c55616b095b3c55b3cad06d160941a4ff2c48b86c0d2fe4bbebc9a66a158",
                "0x5520f32d18618de62efc1c8868515a99fe294e4aeb870089b621d8051c874c8",
                "0x8f883fee1bd35a76adbb0937188615239ab18485e63147f05aa5ebb4a6c65a",
                "0x7ccc05661a74b8413ee232a0c44f0273af07671887ae967c7aa7b1abf0f3784",
                "0x31cf947d9e4b8044d0c647548d8e2798c01cc10d1ce1f4409f3cc4501728095",
                "0x46e220b83e001ca3d20373dea27c00b79c82866d63c7b08fccfe328bdab009a",
                "0x22199a06f9d8fe56a1c97c2264408f510f3db4f8c2243d817ef9f3af469ec29",
                "0x239e01c407f3443c44f6840324d21208d8a21e12c52c707985f7e68666a1abe",
                "0x314b93e1f59a7800da83a130721d296b5d3b3e65b15b58668e5170d9f537744",
                "0x4fd8ab69a23d87aaaddf349b02815c204589c9f26c705d0db1376d83ae90d8d",
                "0x6f1d634be2757bf5375025507bb1cf92ade5b43ab31c369813c833f787ddc11",
                "0x64dc49730b299517aa8a1ef57903053f584f54f5aa37fb4758edc608f37bb35",
                "0x19bda979d8083f89fdc49808127b124a75237b7aca9273f8fc28fca5318fb5",
                "0x5be32d97a93ff8b4e5226e020579a4f467bcf2b321a37543910e5c35e38f288",
                "0x76a8df1e8867cb5200fd3685b95185c40ce737e7d47293bb56122ea1393b573",
                "0x1c1abbd482b750d5ef4e4caa32697d02cbc4e4adeaadb6feb791e96a62e2f45",
                "0x6d3b26cd394e3f2441fbce9e74dee6a63372f35e29aedabf1d0758a22b52e1",
                "0x56517a3b18d4f7ef1fb4ff5d973604d40f5a7cbd6d9693b818a7d74163b8b7d",
                "0x49dc474846c0e4cddb58b02d23bf2ddbec635f1bde9c9ee7792e7f8478bdd57",
                "0x700143e46205c6e2eaee736e81a37e6e086b976aed4f840cd29325f8b69a6c3",
                "0x490314fc119e93430508de1c3f247ab6db1a00fb1f0b17388abb9b1b20b9e7b",
                "0x689bc7459d8b064dedf43fd3db112fbe9210c8a031e962de25b24480732ec42",
                "0xc1150cf06d5f843d0710ea73c4620679ae09df42b3544c0270db1fe1b88488",
                "0x67969e63a213ad339c23c4d670d041c5031c7c8a7998da32141b0d8a9f0b413",
                "0x7bfae97814e4ee2108d7d1aa801c5bfa11219c3dacc393c51515650a6aecf0d",
                "0x4b56c022d20dcd6c2c96d7c004f3fbdca50af1dd8c141645a087b8b510ca5a0",
                "0x5fe4b90bb4f675c339c2739ecc80db219595b06a93a7d1e5efe983195e5356",
                "0x5311da754727eae25b5e52e48990581008982327bc5f37fd7bc2d4a07cbd212",
                "0x6d30dab19a250efbd2d95c2c3b393db51298480525f875f229a58a597ea876c",
                "0x682481b5740d7dad8a0b7563aaa44a458e84ffcb40f8e679f5f2a6c5ef62f3c",
                "0x6d9caa3c7831b006c70e09782ff9b8aa2d119eb2e522d2814aeeb3a00044b69",
                "0x8ceaf4593ede840fd040536b2c5ac9722e410a8d966c64f8a343195742bdd9",
                "0x2ffcb38176f529682ddf5448dd93bae260d02491e9e225ae2356e72a8cb0316",
                "0x3a93cb315625cc7f96b84bf2581c431641c9058eaaad1d610d4e190e0a84ceb",
                "0x5bb24f34c95d330b149783fbb5dea3773d298f7383f6b1b7bd52f91ed5ded37",
                "0x6827c59a8cd8d57a188b747252fbb46edbf0d3fe01923286b2b34ac3b32b0c9",
                "0x13cacc98c36d791ae0eb0c243a938cf1af3d8450f420864567cae1366f89670",
                "0x3766a64f4334a35f7a142930152153c1475e6f2fb461e061d5cd0547c6dfb78",
                "0x129f2288c3e24da30f853cb3390a1eb58b46008b1561b2be916510f92677f36",
                "0x49bf6e91f1b41b6e78f100115a6d00fcd616c4281daf71db8eac6dd16eb5684",
                "0x775b7727c3a5de89c525894e9b9b5d3c3f3aee960e99b250db674e5952705d8",
                "0x3672166bbe1842ef630d2151b8f18abcd1b916577494cd47b1f28adcb28cddc",
                "0x65095bc14297383b9f797210bac6d96f5ef306bedf7cfa2a9f3196743c41e7c",
                "0x53430af6b86dc6a81d6d5edefa90e995f418a2e574d072912c777762ffc5d84",
                "0x67860da8fba45cd6f69a9bd61e37e8807728858a96c952b29c7fd6fed374a67",
                "0x382d3290feea80d22d53ffe6c21b02619dd0d588a53cc93ff8bd692cf7c906d",
                "0x4c78257e753244981fd9712ac8711b9a28bdb1465029b79ee7b504291ddc0ca",
                "0xeb59f662fe7422ecce60f8e2ee691b9cda13a78a4a25db96f66672cb4f84d5",
                "0x27c8406780f93b3094190f6b5542fd62836a88439cbf2529f8c7caf0ceff605",
                "0x24bafe3ffca6012566c84b062dd3980af897ff79e32061e932ba0f6a5be394e",
                "0x3e5f10ec27907b16dacc97a7a155c59b88a0bfb9357459de1ea8a80415e3301",
                "0x37968e4606b990fa5ed2186df61d7bfa118df967a29da6da544dfe22e051364",
                "0x4d1cf2efb3a03dc3382865c452cd9ff55e3ed2acf9067223ed524dc58f5c670",
                "0x13811725d6bb1725db17a5ce549c7bd876a816b2485508e56531e8d963d2734",
                "0x2a323d92cbbab471df11d8406daf1d80f7238946c5e5f1d6239cbc9bb6ff3b5",
                "0x2a9f350f4ee5beebe996755791dd6b9304e8a652d0a4bb0247a81e431acd0b0",
                "0x66d68c9857ad417f01394cb080437730955545792ff8d1e37ed07edd397a664",
                "0x2b8855748030d9b1bb62b42a5423e3fe7214614dc95bafe5e997bfac07008a1",
                "0xf570ca81ea8003d2d208a4e8213db4a80c6c94a8b4683fe002bc8e42684955",
                "0x4ce18da07d6feb2baee0a4925b5ffefa93776ff9931c4754becaa0f4d48f60e",
                "0x37687fb181fd9497337158a8fb2665320819d735f48fd9cfa506eaef41f30fd",
                "0x7b9877237609543867f2dc0845252fc92d97d69fee5854b263577878fc40722",
                "0x5a709abc30af0683f4b6ed2a8f0cbdc2573c57df48656c9d4c8b4191c569e92",
                "0x7a8ec21bc28e915711e646403ee5f0a7a847ca214de9ca08a6805100fc44d19",
                "0x27fd5c00d12b1579d471beb10aa653cdd0212c07c1aa110e84037fc886fb58c",
                "0x3d0f5088d4bcd5214f74ae029d46035af5499daf38e4c25048b00865a4a182d",
                "0x3acfbf69aaa9aa53ce4a119e080d459f3382d473bf8d550bcf5c2ee97d660ce",
                "0x367a599dad9ccc5d5d78f524e5f5803596edf9302d01f6ed236ba19a24fbb82",
                "0x396f80c78b6640b17edfada14cbbdb6495c381aceebc8ae436c86355d51ba14"
            ]
        },
        "id": 1
    }
]
```

### Solution

jsonrpsee supports batched requests from what I can see [here](https://docs.rs/jsonrpsee/latest/jsonrpsee/async_client/struct.Client.html#method.batch_request) but will need to figure out how to integrate this with Madara.

### Are you willing to help with this request?

Yes!

### PR DESCRIPTION
**Pull request by apoorvsadana**
The version middleware doesn't handle batched requests (i.e. array of JSON RPC reuqests). This fixes that. 

Resolves #313

### CODE REVIEW

File: crates/node/src/service/rpc/middleware.rs [hunk 1]
```diff
@@ -267,18 +267,30 @@ async fn add_rpc_version_to_method(req: &mut hyper::Request<Body>) -> Result<(),
...
-        json["method"] = Value::String(new_method);
+    // in case of batched requests, the request is an array of JSON-RPC requests
+    let mut batched_request = false;
+    let mut items = if let Value::Array(items) = json {
+        batched_request = true;
+        items
     } else {
-        return Err(VersionMiddlewareError::InvalidRequestFormat);
+        vec![json]
+    };
```
Comment (antiyro) [inline crates/node/src/service/rpc/middleware.rs:274]: Could we do an helper function for batched_request like:

```rust
fn is_batched_request(json: &Value) -> Option<&Vec<Value>> {
    match json {
        Value::Array(items) => Some(items),
        _ => None,
    }
}
```

Comment (antiyro) [reply crates/node/src/service/rpc/middleware.rs:274]: Not mandatory but it would be cleaner

**Review by antiyro — COMMENTED** [review]
lgtm

File: crates/node/src/service/rpc/middleware.rs (hunk 1 above)
Comment (apoorvsadana) [reply crates/node/src/service/rpc/middleware.rs:274]: Hmm, although making `is_batched_request` return a optional vector looks non intuitive. I can maybe change it to `get_items_from_request` but then I would need to return a tuple - (items, is_batched_request)

**Comment by cchudant** [comment]
Oh, thank you i've thought about this problem
Also, while you're at it, there was something else i've noticed. [This looks wrong](https://github.com/madara-alliance/madara/blob/fa371bd9c493a5da0cfd86a7ba4722bab9616432/crates/node/src/service/rpc/middleware.rs#L251), right? the index should not be 0, it should match the one from the request..? @apoorvsadana 

i believe this is also wrong in the case of batched requests

**Comment by apoorvsadana** [comment]
> Also, while you're at it, there was something else i've noticed. [This looks wrong](https://github.com/madara-alliance/madara/blob/fa371bd9c493a5da0cfd86a7ba4722bab9616432/crates/node/src/service/rpc/middleware.rs#L251), right? the index should not be 0, it should match the one from the request..? @apoorvsadana

You're right! Thanks for pointing it out. I have changed the code now so that requests without `method` are sent directly to the node and the errors of each request are returned respectively.

File: crates/node/src/service/rpc/middleware.rs [hunk 2]
```diff
@@ -248,7 +243,7 @@ where
                     let body = json!({
                         "jsonrpc": "2.0",
                         "error": error,
-                        "id": 0
+                        "id": null
```
Comment (cchudant) [inline crates/node/src/service/rpc/middleware.rs:246]: ah so we can just null out that field, okay
i guess that makes sense

File: crates/node/src/service/rpc/middleware.rs [hunk 3]
```diff
@@ -267,18 +262,29 @@ async fn add_rpc_version_to_method(req: &mut hyper::Request<Body>) -> Result<(),
     let version = RpcVersion::from_request_path(&path)?;
 
     let whole_body = hyper::body::to_bytes(req.body_mut()).await?;
-    let mut json: Value = serde_json::from_slice(&whole_body)?;
-
-    if let Some(method) = json.get_mut("method").as_deref().and_then(Value::as_str) {
-        let new_method = format!("starknet_{}_{}", version.name(), method.strip_prefix("starknet_").unwrap_or(method));
+    let json: Value = serde_json::from_slice(&whole_body)?;
```
Comment (cchudant) [inline crates/node/src/service/rpc/middleware.rs:265]: i really don't like the fact that we're deserializing and reserializing the body like that :pensive: this has a perf cost, especially with serde_json::Value
but that isnt the scope of this PR i guess..

**Review by cchudant — APPROVED** [review]

File: crates/node/src/service/rpc/middleware.rs (hunk 3 above)
Comment (apoorvsadana) [reply crates/node/src/service/rpc/middleware.rs:265]: Ya we can do that in a new PR probably, I can create an issue if you like. Do you've any specific suggestions?

**Review by antiyro — APPROVED** [review]

File: crates/node/src/service/rpc/middleware.rs (hunk 3 above)
Comment (cchudant) [reply crates/node/src/service/rpc/middleware.rs:265]: i think it would require us to handle versions very differently

the problem i have with parsing requests to a serde_json::Value is that it looks like this https://docs.rs/serde_json/latest/serde_json/enum.Value.html
it does one heap allocation per object, string and array, recursively for the whole request and it's really unnecessary
also, their Object(Map<... variant is a BTreeMap, which is really really pushing it - it does a ton of allocs, as you would expect

parsing a concrete struct is much cheaper since nested structs and enums only require one allocation as a whole unless there's a Box or Vec or such in between, so it's not that we're deserializing it twice for nothing, we're actually deserializing it first in the most inefficient way first and then deserializing it again in an okay form

(it's not a problem of the serde_json library, their serde_json::Value type is very sensible, it's just that we should avoid it in such a critical path)

Comment (cchudant) [reply crates/node/src/service/rpc/middleware.rs:265]: let's make an issue, right

Comment (apoorvsadana) [reply crates/node/src/service/rpc/middleware.rs:265]: done #322
